export const CACHE_PREFIX_KEYS = {
    Stakers: 'stakers-',
    ClaimOnBehalfItems: 'claim-on-behalf',
    TokenTransactions: 'token-transactions',
    LiquidityPoolPnl: 'liquidity-pool-pnl-',
    LiquidityPoolTransactions: 'liquidity-pool-tx-',
    Markets: 'markets-',
    Trades: 'trades-',
    OptionTransactions: 'option-transactions-',
    RangedMarkets: 'ranged-markets',
    PositionBalance: 'position-balance',
    RangePositionBalance: 'range-position-balance',
    ReferralTransactions: 'referral-transactions',
    ReferredTraders: 'referred-traders',
    Referrers: 'referrers',

    VaultUserTransactions: 'vault-user-transactions',
    VaultPnl: 'vault-pnl',
    VaultTransactions: 'vault-transactions',
};
