#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if [ -f check_translations.js ]
then
  translationsAdded=$(node check_translations.js)

  if [ ! -z "$translationsAdded" ]
  then
    touch .commit
  fi
else
  echo "check_translations.js doesn't exist. Translations will not be applied."
fi